### ISSUE TITLE
Allow regular ticket reference as first word of message instead of URL

### ISSUE THREAD

**Issue by prayerslayer** [zalando-bus/turnstile#37]
**Not cool**: Writing `https://github.com/zalando/turnstile/issues/123` at the beginning of every commit message.

**Cool**: Writing `#123` at the beginning of every commit message. Optional further information (like repository or even full URL) could be placed afterwards in parentheses like `#123 (zalando/turnstile)`.

(Of course this depends on the SCM system you're using, should work equally well e.g. for Stash.)

**Comment by jmcs** [comment]
For reference: https://help.github.com/articles/writing-on-github/#references

**Comment by jmcs** [comment]
Will be available in turnstile 2.2
